### ISSUE TITLE
Ensure Inhale/Exhale state lasts no longer than 10 seconds

### ISSUE THREAD

**Issue by frankvanbever** [beademingstoestel/python_daemon#13]
AC:
- Add Arduino FSM state handling to python code
- Raise an alarm if the inhale state is maintained for longer than 10 seconds
- Raise an alarm if the exhale state is maintained for longer than 10 seconds

**Comment by Merwanski** [comment]
check update [ALARM] analyse the time inhale / exhale of multiple breathing cycle (mongo database) #33
