### ISSUE TITLE
Pressure below PEEP

### ISSUE THREAD

**Issue by frankvanbever** [beademingstoestel/python_daemon#14]
This is a difficult one. Pressure below PEEP might indicate the patient attempts to breathe. There are 3 approaches:

- Timing based
  "based on bpm, we derive minimal exhalation time, end of this period we look at pressure for diagnostic, then we go to waiting for trigger mode DOCTOR also says: wait minimal time "
- Derivative based
  when we see p<peep, we look into derivative of p: if derivative changes from increasng to decreasing -> trigger patient inhaling, if derivative does not change --> leak/broken peep --> warning
- When the pressure goes below PEEP and the Volume figure does not change then we detected an underpressure problem!

AC:
- Determine the most reliable method
- Raise an alarm is pressure is below PEEP when the patient is not inhaling.

**Comment by Merwanski** [comment]
check [ALARM] detect when the pressure goes below a "peep" threshold TBD during the exhale period T #30
